# Generated by Django 4.0 on 2022-04-10 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('PR', 'Программист'), ('MN', 'Менеджер')], max_length=2, verbose_name='Должность')),
                ('salary', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Оклад')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудник',
            },
        ),
    ]
